server:
  port: 8080

spring:
  application:
    name: hrms-backend

  # PostgreSQL Configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # MongoDB Configuration
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      auto-index-creation: true

  # Mail Server Config
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ADDRESS_USERNAME}
    password: ${MAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  # Upload Configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      file-size-threshold: 2KB

  # Create uploads directory
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${file.upload-dir}

  # Disable static resource
  mvc:
    static-path-pattern: /static/**

# File storage directory
file:
  upload-dir: uploads
app:
  base-url: ${APP_BASE_URL}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXP}
      refresh-token:
        expiration: ${JWT_REFRESH_EXP}
    otp:
      expiration: ${OTP_EXP}
      length: ${OTP_LENGTH}
  admin:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
    name: ${ADMIN_NAME}

cors:
  allowed-origins: ${ALLOWED_ORIGINS}
  allowed-methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
  allowed-headers: "*"
  exposed-headers: "Authorization"
  allow-credentials: true