server:
  port: 8080

spring:
  application:
    name: hrms-backend

  # PostgreSQL Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/hrmf
    username: postgres
    password: postgres

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # MongoDB Configuration
  data:
    mongodb:
      uri: mongodb://localhost:27017/hrms
#      host: localhost
#      port: 27017
#      database: hrms
      auto-index-creation: true

  # Mail Server Config
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ADDRESS_USERNAME:anontom90@gmail.com}
    password: ${MAIL_APP_PASSWORD:ksd slkd lkd}
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true

  # Upload Configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      file-size-threshold: 2KB

  # Create uploads directory
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${file.upload-dir}

  # Disable static resource
  mvc:
    static-path-pattern: /static/**

# File storage directory
file:
  upload-dir: uploads
app:
  base-url: http://localhost:8080

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 24 hours in milliseconds
      refresh-token:
        expiration: 604800000 # 7 days in milliseconds
    otp:
      expiration: 300  # 5 minutes in seconds
      length: 6
  admin:
    email: ${ADMIN_EMAIL:superadmin@hrms.com}
    password: ${ADMIN_PASSWORD:SuperAdmin@123}
    name: ${ADMIN_NAME:System Super Admin}

cors:
  allowed-origins: "http://localhost:3000,http://localhost:4200"
  allowed-methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
  allowed-headers: "*"
  exposed-headers: "Authorization"
  allow-credentials: true